del /Q bin-win32\*.log
del /Q bin-win32\*.docid
del /Q bin-win32\*.index
del /Q bin-win32\*.offset
del /Q bin-win32\*.tf
del /Q bin-win32\*.dat
del /Q bin-win32\output\*.*
del /Q bin-win32\output\seg\*.*
del /Q bin-win32\output\GBK\*.*
del /Q bin-win32\output\UTF8\*.*
del /Q bin-win32\output\scan\*.*
del /Q bin-win32\log.html
del /Q bin-win32\trainrule.xml
del /Q bin-win32\RR_Data.txt
del /Q bin-win32\CoreDict.pdat
del /Q bin-win32\MatchWord.txt
del /Q bin-win32\DataFile\data.txt
del /Q bin-win32\DataFile\data.topic.txt
del /Q bin-win32\DataFile\RunLog.txt
del /Q bin-win32\result.xml
del /Q bin-win32\field.dat.pdat
del /Q Data\*.log
del /Q Data\*.err
del /Q Data\Data\*.log
del /Q Data\Data\*.err
del /Q bin-win32\*.log
del /Q bin-win32\*.err
del /Q bin-win32\*.pdb
del /Q bin-win32\*.ilk
del /Q bin-win32\RR*.txt
del /Q bin-win64\*.log
del /Q bin-win64\*.docid
del /Q bin-win64\*.index
del /Q bin-win64\*.offset
del /Q bin-win64\*.tf
del /Q bin-win64\*.dat
del /Q bin-win64\output\*.*
del /Q bin-win64\output\seg\*.*
del /Q bin-win64\output\GBK\*.*
del /Q bin-win64\output\UTF8\*.*
del /Q bin-win64\output\scan\*.*
del /Q bin-win64\log.html
del /Q bin-win64\trainrule.xml
del /Q bin-win64\RR_Data.txt
del /Q bin-win64\CoreDict.pdat
del /Q bin-win64\MatchWord.txt
del /Q bin-win64\DataFile\data.txt
del /Q bin-win64\DataFile\data.topic.txt
del /Q bin-win64\DataFile\RunLog.txt
del /Q bin-win64\result.xml
del /Q bin-win64\field.dat.pdat
del /Q bin-win64\Data\*.log
del /Q bin-win64\Data\*.err
del /Q bin-win64\Data\Data\*.log
del /Q bin-win64\Data\Data\*.err
del /Q bin-win64\*.log
del /Q bin-win64\*.err
del /Q bin-win64\*.pdb
del /Q bin-win64\*.ilk
del /Q bin-win64\RR*.txt


