copy /y NLPIR-Parser平台授权\NLPIRParser.user ..\..\NLPIR-Parser\Data
copy  /y ".\NLPIR-ICTCLAS分词系统授权\NLPIR.user"  "..\..\NLPIR SDK\NLPIR-ICTCLAS\Data"
copy  /y ".\classifier规则分类授权\classifier.user"  "..\..\NLPIR SDK\Classify\Data"
copy  /y ".\classifier深度学习分类授权\deepclassifier.user"  "..\..\NLPIR SDK\DeepClassifier\Data"
copy  /y ".\cluster聚类授权\cluster.user"  "..\..\NLPIR SDK\Cluster\Data"
copy  /y ".\DocExtractor文档提取授权\DocExtractor.user"  "..\..\NLPIR SDK\DocExtractor\Data"
copy  /y ".\JZSearch精准搜索引擎授权\JZSearch.user"  "..\..\NLPIR SDK\JZSearch\Data"
copy  /y ".\KeyExtract关键词提取授权\KeyExtract.user"  "..\..\NLPIR SDK\KeyExtract\Data"
copy  /y ".\KeyExtract关键词提取授权\KeyExtract.user"  "..\..\NLPIR SDK\NLPIR-ICTCLAS\Data"
copy  /y ".\KeyScanner九眼智能扫描授权\KeyScan.user"  "..\..\NLPIR SDK\KeyScanner\Data"
copy  /y ".\LJSpider精准采集器\LJSpider.user"  ..\..\NLPIR-Parser\LJSpider\
copy  /y ".\NewWordFinder新词发现授权\NewWordFinder.user"  "..\..\NLPIR SDK\NewWordFinder\Data"
copy  /y ".\NewWordFinder新词发现授权\NewWordFinder.user"  "..\..\NLPIR SDK\NLPIR-ICTCLAS\Data"
copy  /y ".\RedupRemover去重授权\LJRedupRemover.user"  "..\..\NLPIR SDK\RedupRemover\Data"
copy  /y ".\SplitSentence分句系统\SplitSentence.user"  "..\..\NLPIR SDK\SplitSentence\Data"
copy  /y ".\SentimentNew情感分析授权\Sentiment.user"  "..\..\NLPIR SDK\SentimentNew\Data"
copy  /y ".\SentimentNew情感分析授权\Sentiment.user"  "..\..\NLPIR SDK\SentimentAnalysis\Data"
copy  /y ".\Summary自动摘要提取授权\Summary.user"  "..\..\NLPIR SDK\Summary\Data"
copy  /y ".\TxtExtractor文档抽取器\TxtExtractor.user"  "..\..\NLPIR-Parser\TxtExtractor\"
