SummarySystem:   ../../../Src/Summary/Sample/SummarySystem.cpp ../../../Src/Summary/API/LJSummary.h
	 g++ ../../../Src/Summary/Sample/SummarySystem.cpp -L../../../bin/Summary -lLJSummary -Wall -Wunused -O3 -DOS_LINUX  -o ../../../bin/Summary/SummarySystem
clean:
	rm -f *.o ../../bin/Summary/SummarySystem