
test: ../../../Src/SplitSentence/Sample.cpp ../../../Src/Utility/ReadFile.cpp ../../../Src/SplitSentence/SplitSentence.h ../../../Src/Utility/ReadFile.h
	 g++ ../../../Src/SplitSentence/Sample.cpp ../../../Src/Utility/ReadFile.cpp -g -L. -lpthread -L../../../bin/SplitSentence/ -lSplitSentence -Wall -Wunused -O3 -DOS_LINUX  -o ../../../bin/SplitSentence/Sample
